# Generated by Django 5.0.6 on 2024-09-04 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_websitestyle_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='link',
            name='color',
        ),
        migrations.RemoveField(
            model_name='link',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='link',
            name='name',
        ),
        migrations.RemoveField(
            model_name='link',
            name='url',
        ),
        migrations.RemoveField(
            model_name='websitestyle',
            name='background_color',
        ),
        migrations.RemoveField(
            model_name='websitestyle',
            name='font',
        ),
        migrations.RemoveField(
            model_name='websitestyle',
            name='font_size',
        ),
        migrations.RemoveField(
            model_name='websitestyle',
            name='text_color',
        ),
        migrations.AddField(
            model_name='link',
            name='facebook_username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='link',
            name='github_username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='link',
            name='instagram_username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='link',
            name='linkedin_username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='link',
            name='project_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='link',
            name='telegram_username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='link',
            name='tiktok_username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='link',
            name='twitter_username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='link',
            name='whatsapp_username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='link',
            name='youtube_username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
