name: Django CI/CD

on:
  push:
    branches: [ main ]  # yoki master, asosiy branch nomiga qarab

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: ${{ secrets.KNOWN_HOSTS }}
      
      - name: Deploy to server
        run: |
          ssh -o StrictHostKeyChecking=accept-new root@77.232.128.142 << 'EOF'
          cd /home/Proflio
          git pull
          source /home/venv/bin/activate
          pip install -r requirements.txt
          python manage.py migrate
          python manage.py collectstatic --noinput
          supervisorctl restart all
          EOF

      - name: Debug SSH connection
        env:
          HOST: 77.232.128.142
          USER: root
        run: |
          ssh -vvv -o StrictHostKeyChecking=accept-new $USER@$HOST echo "SSH connection successful"
