name: Deploy to Server

on:
  push:
    branches: [ master ]  # yoki master, asosiy branch nomiga qarab

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Install SSH Key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        known_hosts: ${{ secrets.KNOWN_HOSTS }}
    
    - name: Deploy to server
      run: |
        ssh -o StrictHostKeyChecking=accept-new -v root@77.232.128.142 << 'EOF'
          cd /home/Proflio
          git pull 
          source /home/env/bin/activate
          pip install -r req.txt
          python manage.py migrate
          python manage.py collectstatic --noinput
          supervisorctl restart all
        EOF
